In [ ]:
import numpy as np

In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
array=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype=float)
print(array)
print(array.ndim)

[[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]
 [10. 11. 12.]]
2


In [ ]:
print(array.shape)

(4, 3)


In [ ]:
print(array.size)

12


In [ ]:
print(array.dtype)

float64


In [ ]:
a=[10,20,30,40,50,60,70,80,90,100]
array1=np.array(a)
array1
print(array1.dtype)
print(type(array1))

int64
<class 'numpy.ndarray'>


In [ ]:
z=np.random.random((2,2))
z

array([[0.04439111, 0.37131035],
       [0.63150156, 0.77130389]])

In [ ]:
f=np.arange(1,10,1)
f

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
f=np.arange(1,10,2)
f

array([1, 3, 5, 7, 9])

In [ ]:
lz=np.linspace(0,5,10)
lz

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [ ]:
import numpy as nd
array=nd.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]])
newarray=array.reshape(4,2,2)
newarray

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]],

       [[13, 14],
        [15, 16]]])

In [ ]:

flarrays=array.flatten()
flarrays


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
temp=array[:2,::2]
temp

array([[1, 3],
       [5, 7]])

In [ ]:
cond=array>2
temp=array[cond]
temp

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [ ]:
print(array.T)

array([[ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15],
       [ 4,  8, 12, 16]])

In [ ]:
print('maximum value:',array.max(axis=0))
print('maximum value:',array.max(axis=1))

maximum value: [13 14 15 16]
maximum value: [ 4  8 12 16]


In [ ]:
print(array.cumsum(axis=1))

[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]
 [13 27 42 58]]


In [ ]:
print(array.cumsum(axis=1))

[[ 1  3  6 10]
 [ 5 11 18 26]
 [ 9 19 30 42]
 [13 27 42 58]]


In [ ]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
print(np.vstack((a,b,c)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
print(np.hstack((a,b,c)))

[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [ ]:
import numpy as np

a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.array([[9,10],[11,12]])
print(np.concatenate((a,b,c)))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [ ]:
a=np.array([[1,3,5,7,9,11],
            [2,4,6,8,10,12]])

In [ ]:
np.hsplit(a,6)

[array([[1],
        [2]]), array([[3],
        [4]]), array([[5],
        [6]]), array([[7],
        [8]]), array([[ 9],
        [10]]), array([[11],
        [12]])]

In [ ]:
np.vsplit(a,2)

[array([[ 1,  3,  5,  7,  9, 11]]), array([[ 2,  4,  6,  8, 10, 12]])]

Broadcasting:Integral Transform transforming from time domain to frequency domain.


In [ ]:
#Brodcasting:
import numpy as np

a=np.array([10,20,30])000
b=2
print(a*b)

c=[2,2,2]
print(a*c)

[20 40 60]
[20 40 60]
